name: Week 3
on:
  push:
    branches:
      - week3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(cat ./.bit/.progress)
        
      - name: Cypress run
        run: npm install
        uses: cypress-io/github-action@v2
        with:
          project: ./
          spec: .bit/tests/5-test.js

