name: Week 2
on:
  push:
    branches:
      - week2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(cat ./.bit/.progress)
        
      - name: Step 1
        env:
          FUNCTION_URL: ${{ secrets.FUNCTION_URL }}
        run: |
          npm install node-fetch
          npm install fs
          npm install form-data
          node .bit/tests/2-test.js
      
      - name: Step 1
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          SUBSCRIPTION_KEY: ${{ secrets.SUBSCRIPTION_KEY }}
